name: fantasticon_flutter
version: 1.0.0
homepage: https://github.com/Jupi007/fantasticon_flutter
description: Convert all *.svg icons from dir to icon-font (.ttf) and generates flutter compatible dart class using fantasticon.

environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  recase: ^4.0.0
  args: ^2.0.0
  meta: ^1.3.0
  path: ^1.8.0

dev_dependencies: 
  pedantic: ^1.11.0

executables: 
  fantasticon_flutter: fantasticon_flutter
